# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Baseapp' do

end

target 'BaseappTests' do

end

target 'BaseappUITests' do

end

